CANNOT_OPEN_CONFIG_FILE = "Error: cannot open the config file!"
MALFORMED_CONFIG_FILE = "Error: malformed config file!"
INVALID_CONFIG_VALUES = "Error: invalid value(s) in config file!"
INVALID_BOT_TOKEN = "Error: invalid bot token!"
BOT_STARTED_MESSAGE = "🚀 Bot started"
BOT_STOPPING_MESSAGE = "🛑 Stopping bot!"
BOT_STOPPED_MESSAGE = "🛑 Bot stopped"
BOT_ERROR_MESSAGE = "‼️ An error has occurred!"
EMPTY_LOG_FILE = "Log file is empty"
SYSTEM_MESSAGES_CHANNEL_ERROR = "Invalid system messages channel ID, or bot not in channel, or bot doesn't have the permission to send messages!"
START_MESSAGE = ("This bot was made for personal use\n"
				"https://github.com/DerivativeOfLog7/uscita-domenica-bot")
DEFAULT_MSG = "Uscita domenica"
OPT_1 = "Ci sono a pranzo"
OPT_2 = "Ci sono dopo pranzo"
OPT_3 = "Non ci sono"
OPT_4 = "Non lo so"